<?php use \ModelColumn ?>
/**
 * This is an autogenerated model class.
 * @package <?php echo $package ?> 
 * @subpackage models
 * @version <?php echo date('Y-m-d h:i:s') ?> 
<?php foreach ($queryMethods as $method): ?>
 * @method <?php echo $modelName ?>Query <?php echo $method ?>

<?php endforeach ?>
 */
class <?php echo $modelName ?>Query extends myQuery {

	/**
	 *
	 * @return <?php echo $modelName ?>Query
	 */
	public static function create(<?php echo $className ?> $table = null, array $params = null) {
		if ($table === null) $table = <?php echo $className ?>::getInstance();
		return new <?php echo $modelName ?>Query($table, $params);
	}

<?php foreach ($fields as $field): $field instanceof TplField ?>
<?php if ($field->getType() === ModelColumn::T_BOOL): ?>
	public function whereIs<?php echo $field->getVarName(true) ?>() {
		return $this->where($this->getQualifiedName('<?php echo $field->getName() ?>') . ' = ?', true);
	}

	public function whereIsNot<?php echo $field->getVarName(true) ?>() {
		return $this->where($this->getQualifiedName('<?php echo $field->getName() ?>') . ' = ?', false);
	}

<?php endif ?>
<?php endforeach; ?>
}