<?php use \ModelColumn ?>
<?php if (isset($namespace)): ?>
namespace <?php echo $namespace ?>;
<?php endif ?>

/**
 * This is an autogenerated model class.
 * @category <?php echo $this->modelCategory, PHP_EOL ?>
 * @package <?php echo $this->modelPackage, PHP_EOL ?>
 * @subpackage Query
<?php if ($version): ?>
 * @since <?php echo $version ?>

<?php endif ?>
<?php foreach ($queryMethods as $method): ?>
 * @method <?php echo $modelName ?>Query <?php echo $method ?>

<?php endforeach ?>
 */
class <?php echo $modelName ?>Query extends <?php echo $baseQueryName ?> {

	/**
	 *
	 * @return <?php echo $modelName ?>Query
	 */
	public static function create(ModelTable $table = null, array $params = null) {
		if ($table === null) $table = <?php echo $className ?>::getInstance();
		return new <?php echo $modelName ?>Query($table, $params);
	}

<?php foreach ($fields as $field): $field instanceof TplField ?>
<?php if ($field->getType() === ModelColumn::T_BOOL): ?>
	public function whereIs<?php echo $field->getVarName(true) ?>() {
		return $this->where($this->getQualifiedName('<?php echo $field->getName() ?>') . ' = ?', true);
	}

	public function whereIsNot<?php echo $field->getVarName(true) ?>() {
		return $this->where($this->getQualifiedName('<?php echo $field->getName() ?>') . ' = ?', false);
	}

<?php endif ?>
<?php endforeach; ?>
}
