config.node: eoze\application

namespace: eoze\default_user_namespace

name: Eoze Application
title: Eoze Application

author: Unknown
description: This is an application based on eoze framework!
licence: Licence - GNU/GPL v.3
