config.node: eoko\module

locations:

  eoko:
    path: %eoze%/modules
    url: %eoze%/modules
    namespace: eoko\modules

#  eoko-defaults:
#    path: %lib%/modules
#    url: %lib%/modules
#    namespace: eoko\modules

used:

  eoko:
    - GridModule
    - root
    - AjaxRouter
    - MediaManager
    - CrocodocViewer
    - AccessControl
    - TreeMenu
    - IconProvider
    - TabModule
    - ModuleGroupModule
    - MercurialConsole
    - DirectModule
    - DirectGridModule
    - Prolix
    - Kepler
    - UserPreferences
    - DataSnapshots
    - EozeExt4
    - CkEditor
