/**
 * File autogenerated on <?php echo date('Y-m-d H:i:s') ?>

 */
<?php echo $baseClass ?> {

}
<?php foreach ($icons as $icon): ?>
<?php echo $baseClass ?>.<?php echo $icon['class'] ?> {
	background-image: url("<?php echo $icon['url'] ?>") !important;
}
<?php endforeach ?>
